name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    # maquina onde o workflow será executado
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        continue-on-error: true
        with:
          install-comand: npm install
          browser: chrome
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
